-- 0001_init — core schema (SQLite).
--
-- Design notes:
--  * Identifiers are text UUIDs generated by the application, since SQLite has
--    no uuid type or generator.
--  * Timestamps are ISO-8601 text in UTC. SQLite has no date type; text sorts
--    and compares correctly in this format.
--  * Booleans are 0/1 integers.
--  * The ~80% of the model that is identical across Assure / Align / Anchor gets
--    real columns. Framework-specific fields (CSF Tiers and profile statements,
--    800-53 parameter values, origination, baseline membership) live in a JSON
--    `attrs` column so the three products share one schema.

-- ── identity ────────────────────────────────────────────────────────────────
create table users (
  id            text primary key,
  username      text not null unique,
  email         text not null,
  name          text not null default '',
  role          text not null default 'readonly'
                  check (role in ('admin','contributor','auditor','readonly')),
  auth_source   text not null default 'local'
                  check (auth_source in ('local','oidc','saml')),
  password_hash text,                      -- argon2id; null for SSO-only users
  totp_secret   blob,                      -- encrypted with FIELD_ENC_KEY
  disabled      integer not null default 0,
  last_login_at text,
  failed_logins integer not null default 0,
  locked_until  text,
  created_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  check (auth_source <> 'local' or password_hash is not null)
);
create index users_email_idx on users (lower(email));

create table sessions (
  sid          text primary key,
  user_id      text not null references users(id) on delete cascade,
  ip           text,
  user_agent   text,
  created_at   text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  last_seen_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  expires_at   text not null
);
create index sessions_user_idx on sessions (user_id);
create index sessions_expiry_idx on sessions (expires_at);

-- ── audit ───────────────────────────────────────────────────────────────────
-- Append only. Nothing in the application updates or deletes from this table.
create table audit_log (
  id         integer primary key autoincrement,
  ts         text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  actor_id   text references users(id) on delete set null,
  actor_name text not null default 'system',
  ip         text,
  action     text not null,
  entity     text,
  entity_id  text,
  before     text,                          -- JSON
  after      text,                          -- JSON
  request_id text
);
create index audit_log_ts_idx on audit_log (ts desc);
create index audit_log_entity_idx on audit_log (entity, entity_id);

-- ── framework content ───────────────────────────────────────────────────────
create table controls (
  id            text primary key,
  ref           text not null unique,       -- 'GV.OC-01' | 'AC-2(1)' | 'A.5.1'
  title         text not null,
  theme         text not null,              -- Function / family / Annex A theme
  parent_ref    text,                       -- 800-53 enhancements point at their base
  status        text not null default 'not_started'
                  check (status in ('not_started','in_progress','implemented','not_applicable')),
  owner         text not null default '',
  notes         text not null default '',
  mapped        text not null default '',   -- cross-framework reference
  justification text not null default '',   -- applicability / tailoring rationale
  attrs         text not null default '{}', -- JSON
  created_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index controls_theme_idx on controls (theme);
create index controls_status_idx on controls (status);
create index controls_parent_idx on controls (parent_ref);
-- The two attrs lookups the products actually filter on. SQLite cannot index a
-- whole JSON document, so index the expressions instead.
create index controls_priority_idx on controls (json_extract(attrs, '$.priority'));
create index controls_origination_idx on controls (json_extract(attrs, '$.origination'));

create table control_tests (
  id         text primary key,
  control_id text not null references controls(id) on delete cascade,
  tested_on  text not null,
  tester     text not null default '',
  result     text not null check (result in ('Pass','Fail','Partial')),
  note       text not null default '',
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index control_tests_control_idx on control_tests (control_id, tested_on desc);

-- ── evidence ────────────────────────────────────────────────────────────────
create table evidence (
  id             text primary key,
  name           text not null,
  type           text not null default 'Document',
  owner          text not null default '',
  collected_date text,
  next_review    text,
  file_key       text,
  file_name      text,
  file_size      integer,
  file_sha256    text,
  notes          text not null default '',
  created_at     text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at     text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index evidence_collected_idx on evidence (collected_date desc);

create table evidence_controls (
  evidence_id text not null references evidence(id) on delete cascade,
  control_id  text not null references controls(id) on delete cascade,
  primary key (evidence_id, control_id)
);
create index evidence_controls_control_idx on evidence_controls (control_id);

-- ── risk ────────────────────────────────────────────────────────────────────
create table risks (
  id             text primary key,
  seq            integer not null,
  title          text not null,
  description    text not null default '',
  category       text not null default '',
  likelihood     integer not null check (likelihood between 1 and 5),
  impact         integer not null check (impact between 1 and 5),
  res_likelihood integer check (res_likelihood between 1 and 5),
  res_impact     integer check (res_impact between 1 and 5),
  treatment      text not null default 'Mitigate',
  status         text not null default 'Open',
  owner          text not null default '',
  review_date    text,
  accepted_by    text,
  accepted_date  text,
  created_at     text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at     text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index risks_seq_idx on risks (seq);

create table risk_controls (
  risk_id    text not null references risks(id) on delete cascade,
  control_id text not null references controls(id) on delete cascade,
  primary key (risk_id, control_id)
);

-- ── programme state (one row) ───────────────────────────────────────────────
create table programme (
  id          integer primary key check (id = 1),
  scope       text not null default '',
  methodology text not null default '',
  attrs       text not null default '{}',   -- JSON: tiers | system + baseline
  updated_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
insert into programme (id) values (1);

-- ── readiness history (feeds the dashboard trend) ───────────────────────────
create table trend (
  day text primary key,
  pct integer not null check (pct between 0 and 100)
);

-- ── settings ────────────────────────────────────────────────────────────────
create table settings (
  key        text primary key,
  value      text not null,                 -- JSON
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ── background jobs ─────────────────────────────────────────────────────────
-- Replaces pg-boss, which is Postgres-only. A single table plus a polling
-- worker is enough at this scale and keeps the "one file is the database"
-- property intact.
create table jobs (
  id           text primary key,
  name         text not null,
  payload      text not null default '{}',  -- JSON
  run_after    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  started_at   text,
  completed_at text,
  failed_at    text,
  attempts     integer not null default 0,
  last_error   text,
  created_at   text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index jobs_queue_idx on jobs (completed_at, run_after);

-- ── updated_at maintenance ──────────────────────────────────────────────────
create trigger users_touch after update on users for each row
when new.updated_at = old.updated_at   -- guard against re-firing on our own write
begin update users set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id; end;

create trigger controls_touch after update on controls for each row
when new.updated_at = old.updated_at   -- guard against re-firing on our own write
begin update controls set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id; end;

create trigger evidence_touch after update on evidence for each row
when new.updated_at = old.updated_at   -- guard against re-firing on our own write
begin update evidence set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id; end;

create trigger risks_touch after update on risks for each row
when new.updated_at = old.updated_at   -- guard against re-firing on our own write
begin update risks set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id; end;

create trigger programme_touch after update on programme for each row
when new.updated_at = old.updated_at   -- guard against re-firing on our own write
begin update programme set updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') where id = new.id; end;
